# Generated by Django 2.1.7 on 2019-02-26 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_soft_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soft_name', models.CharField(max_length=50, verbose_name='软件名称')),
                ('desc', models.CharField(max_length=100, verbose_name='订单描述')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user.Soft_Category', verbose_name='类别id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
