# Generated by Django 2.1.7 on 2019-02-26 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_New',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0, verbose_name='未读订单数')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_new', to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'db_table': 'order_new',
            },
        ),
    ]
