# Generated by Django 2.1.7 on 2019-02-26 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_order_package_url'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='indent',
        ),
    ]
