# Generated by Django 2.1.7 on 2019-02-26 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='programer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_orders', to=settings.AUTH_USER_MODEL, verbose_name='程序员'),
        ),
    ]
